### ISSUE TITLE
Getter name should follow rust convention

### ISSUE THREAD

**Issue by pickfire** [otaviopace/design-patterns#4]
[Rust API Guidelines for Naming (C-GETTER)](https://rust-lang-nursery.github.io/api-guidelines/naming.html?highlight=getter#getter-names-follow-rust-convention-c-getter) should be reflected in https://github.com/otaviopace/design-patterns/blob/master/behavioral/memento/rust/src/lib.rs#L19-L24 and other files.

Maybe work on this for Hacktoberfest 2018?

**Comment by evaporei** [comment]
Ok, I took a lot of time to respond, sorry!

I can take this soon, definitely :slightly_smiling_face:

**Comment by evaporei** [comment]
I was changing everything as the guidelines said, however because the code is very linked to old design patterns, that not necessarily translate well to Rust, I will let it the way it is, even though it is not the most idiomatic Rust.

It may be easy to translate things like `set_data` to `data_mut`, however things like this:

```rust
fn set_data(&mut self, data1: &str, data2: &str) {
    self.dependent_object1.set_data(data1);
    self.dependent_object2.set_data(data2);
}
```

Make it hard to make these patterns.

Anyway, thanks for pointing out this! I will get better at making Rust projects following the guidelines :slightly_smiling_face:

**Comment by pickfire** [comment]
See the standard library for examples of `data_mut()`, there are tons of libraries using that out there instead of `set_data()`.

```rust
*self.data_mut() = data1;
```

For example https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.get_mut
